apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inahga-org
  namespace: default
spec:
  secretName: inahga-org-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - '*.inahga.org'
  - inahga.org
