apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: inahga@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          route53:
            region: us-west-2
            accessKeyID: AKIAYV7RA74C4XUQG2UH
            secretAccessKeySecretRef:
              name: letsencrypt-route53-key
              key: access-key-secret
