resources:
  - https://docs.projectcalico.org/manifests/tigera-operator.yaml
  - https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/baremetal/deploy.yaml

# https://kubernetes.github.io/ingress-nginx/deploy/baremetal/#via-the-host-network
patches:
  - patch: |-
      - op: replace
        path: /kind
        value: DaemonSet
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ingress-nginx"
