apiVersion: v1
kind: Service
metadata:
  name: revelation
  labels:
    app.kubernetes.io/name: revelation
spec:
  type: NodePort
  ports:
  - name: tcp
    port: 30690
    targetPort: 6900
  selector:
    app.kubernetes.io/name: revelation
