resources:
  - calico-custom-resources.yaml
  - cert-manager
  - https://github.com/kubevirt/kubevirt/releases/download/v0.35.0/kubevirt-cr.yaml

# patches:
#   - patch: |-
#       - op: replace
#         path: /spec/acme/server
#         value: https://acme-v02.api.letsencrypt.org/directory
#     target:
#       kind: ClusterIssuer
#       name: letsencrypt

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: letsencrypt-route53-key
    namespace: cert-manager
    files:
      - secrets/cert-manager/access-key-secret
      - secrets/cert-manager/access-key-id
  - name: inahga-org-ca
    namespace: cert-manager
    files:
      - secrets/cert-manager/tls.key
      - secrets/cert-manager/tls.crt
    type: kubernetes.io/tls
