- name: install defaults
  hosts: all
  vars:
    - ansible_ssh_user: root
    - users:
        - name: aghani
          authorized_keys: https://github.com/inahga.keys

  tasks:
    - name: add users
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: wheel
        state: present
      with_items: "{{ users }}"

    - name: install ssh keys
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.authorized_keys }}"
        exclusive: yes
        state: present
      with_items: "{{ users }}"

    - name: update system
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: configure automatic updates (weekly)
      ansible.builtin.cron:
        name: dnf cron
        job: "dnf update -y"
        minute: "0"
        hour: "0"
        weekday: "5"
        user: root

    - name: set sane sshd defaults
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0600'
        validate: /usr/sbin/sshd -t -f %s
        backup: yes

    - name: reboot the system
      command: reboot
